### ISSUE TITLE
Spotguide: new version of pipeline.yaml and questions form merging

### ISSUE THREAD

**Issue by bonifaido** [banzaicloud/pipeline#1149]
```yaml
questions:
- type: secret
  inputType: password
  targets:
    - name: ...
  group: Docker Hub
  required: true
- type: pipeline
  inputType: enum
  label: 'Service type'
  default: 'ClusterIP'
  required: true
  group: Service
  options:
  - ClusterIP
  - LoadBalancer
  - NodeIP
  targets:
    - deploy_application.deployment.values.application.service.type
- type: pipeline
  inputType: number
  label: 'Service port'
  default: 80
  required: true
  group: Service
  min: 80
  max: 65535
  targets:
    - deploy_application.deployment.values.application.service.port
- type: secret
  inputType: password
  group: Database
  targets:
    # TODO map password to mongodb-password
    - name: ....
    - username: deploy_application.deployment.values.mongodb.mongodbUsername
- type: pipeline
  inputType: string
  label: 'MongoDB database'
  required: false
  default: application
  group: Database
  targets:
    - deploy_application.deployment.values.mongodb.mongodbDatabase
```
