### ISSUE TITLE
Monitoring infra is not getting installed but the UI said it should be.

### ISSUE THREAD

**Issue by baluchicken** [banzaicloud/pipeline#1226]
In case of spotguide monitoring is always turned on, but the infra is not installed to the cluster.

**Comment by baluchicken** [comment]
https://github.com/banzaicloud/ci-pipeline-client/blob/2a80e66bb6b7e40434791a878bfe6752d31db7a3/main.go#L304
This part of the code simply ignores the value if it is empty:
```
  postHooks:
    InstallLogging:
      bucketName: baluchicken-spark-test
      region: eu-west-1
      secretId: 198e9d4187d2789914a35771e4f12da45218a77f67f01eb8695b3fb83081f8b6
    InstallMonitoring: {}
```
InstallMonitoring will not be present in the values

```
postHooks:
    InstallLogging:
      bucketName: baluchicken-spark-test
      region: eu-west-1
      secretId: 198e9d4187d2789914a35771e4f12da45218a77f67f01eb8695b3fb83081f8b6
    InstallMonitoring:
      littlepuppy: appletree
```
Will be present in the values, after the get
