### ISSUE TITLE
New endpoint to retrieve dashboard info for only one cluster

### ISSUE THREAD

**Issue by sancyx** [banzaicloud/pipeline#2112]
Create a new API endpoint for Pipeline UI: `GET {{url}}/dashboard/orgs/:orgId/clusters/:clusterId` to return the following info for a single cluster:

````
createdAt: string
createdBy: string
creatorId: number
name: string (cluster neve)
region: string
status: string (RUNNING, DELETING…)
statusMessage: string (Your cluster is running…….)
cloud: string;
distribution: string
endpoint: string
location: string (only for amazon, google, alibaba)
masterVersion: string (master node K8S version)
clusterGroup: string (optional)
project: string (only for Google)
resourceGroup: string (only for Azure)
nodePools: (list of node pools, name, count, min/max, labels etc.)
cpuUsagePercent: number
memoryUsagePercent: number
nodes: 
Name
creationTime
status
diskPressure: string; // "False"
  frequentUnregisterNetDevice: string; // "Unknown"
  kernelDeadlock: string; // "Unknown"
  memoryPressure: string; // "False"
  networkUnavailable: string; // "False"
  outOfDisk: string; // "False"
  pidPressure: string; // "Unknown"
  allocatable:
cpu: string; //  "3920m";
  ephemeralStorage: string; // "n/a"
  memory: string; // "12706708Ki"
  pods: string; // 110
  capacity:
cpu: string; //  "3920m";
  ephemeralStorage: string; // "n/a"
  memory: string; // "12706708Ki"
  pods: string; // 110
  cpuUsagePercent: number; // 0
  instanceType: string; // "n1-standard-4"
  lastHeartbeatTime: string; // "2018-09-25 12:31:37 +0000 UTC"
  memoryUsagePercent: number; // 17.52089384558144
  ready: string; // "True"
  storageUsagePercent: number; // 0
````
