### ISSUE TITLE
Investigate use of service account IAM roles for pipeline-system

### ISSUE THREAD

**Issue by sancyx** [banzaicloud/pipeline#3344]
Use service account IAM roles instead of node instance role for pipeline installed components like a cluster-autoscaler & velero.

**Comment by sancyx** [comment]
The proposed solution works as follows:

- Pipeline should be preconfigured with AWS Account ID and IAM role name prefix for each component which has to be configured with service account role, something like below:

```
iamRoleServiceAccount:
  clusterAutoscaler:
       accountID: xxxxxxxx
       roleNamePrefix: ClusterAutoscalerRole
  velero:
      accountID: xxxxxxxx
      roleNamePrefix: VeleroRole
```

- Pipeline creates EKS cluster then installs components with IAM role annotated service accounts

- Customer has to enable IAM roles for service accounts on that created cluster then create IAM roles for each component.
For ex. IAM role for Cluster Autoscaler should be named: ClusterAutoscalerRole-<CLUSTER_NAME>. To create IAM roles customer has to retrieve OIDC_PROVIDER url from EKS, which is available after the cluster has been created.
