### ISSUE TITLE
Extend spotguide.yaml with secrets options

### ISSUE THREAD

**Issue by tarokkk** [banzaicloud/pipeline#581]
**Is your feature request related to a problem? Please describe.**
To properly manage applications we should be able to save general secrets (like passwords) to our vault instance. For better user experience we should provide automatically generated default secrets for Spotguides.

**Describe the solution you'd like to see**
Example spotguide section:
```
secrets:
  - name: mysql_credential
     password:
       username: root
       password: [randAlphaNum,randAlpha,randNumeric,randAscii],<length>

  - name: nginx_credential
     htaccess:
       username: root
       password: [randAlphaNum,randAlpha,randNumeric,randAscii],<length>

  - name: mysql_tls
     tls:
       host: ???
       expiration: <days>
```
**Additional context**
This simple snippet is an example how-to define custom secrets. The secret is stored in Vault, tagged with the application id. The secret should be presented on the target Kubernetes cluster. The user after can view/download the relevant part of the secret (like client.crt, client.key).

**Secret types**
Secret types defines the way of the secret Kubernetes secret layout:

- `password`: Kubernetes secret with `username` and `password` field
- `tls`: Kubernetes secret with the following fields:
  - CA.crt
  - CA.key
  - Server.crt
  - Server.key
  - Client.crt
  - Client.key
